=== ftn-dnb/xws/xws-service/data/schemas/naucni_rad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="naucni_rad" xmlns:nr="naucni_rad">
    <xs:element name="NaucniRad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NaslovnaStrana">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naslov" type="xs:string"/>
                            <xs:element maxOccurs="1" name="Autori">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Autor"
                                            type="nr:CTAutor"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Abstrakt">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="preserve"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="KljucneReci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="6" minOccurs="4" name="KljucnaRec"
                                type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Poglavlja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Poglavlje" type="nr:CTPoglavlje"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Reference">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="Referenca" type="nr:CTReferenca"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="CTPoglavlje" mixed="false">
        <xs:sequence>
            <xs:element name="Naslov" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Pasus" type="nr:CTPasus"/>
            <xs:element maxOccurs="1" minOccurs="0" name="Poglavlje" type="nr:CTPoglavlje"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTPasus" mixed="true">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Slika">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="xs:base64Binary"/>
                        <xs:element name="Naziv" type="xs:string"/>
                        <xs:element name="IdReference" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Tabela">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="Red">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element maxOccurs="unbounded" name="Celija" type="xs:string"
                                    />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Lista">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Stavka" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute default="neuredjena" name="Vrsta">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="uredjena"/>
                                <xs:enumeration value="neuredjena"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
            <xs:element name="Tekst">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="xs:string"/>
                        <xs:element name="IdReference" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="CTAutor">
        <xs:sequence>
            <xs:element maxOccurs="1" name="Ime" type="xs:string"/>
            <xs:element maxOccurs="1" name="Prezime" type="xs:string"/>
            <xs:element name="EMail">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".+@.+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="BrojTelefona" type="xs:string"/>
            <xs:element name="ORCID" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{4}-d{4}-d{4}-d{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Ustanova" type="nr:CTNaucnaUstanova"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="CTNaucnaUstanova">
        <xs:sequence>
            <xs:element name="Naziv" nillable="false" type="xs:string"/>
            <xs:element name="Adresa" type="nr:CTAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:string"/>
            <xs:element name="Grad" type="xs:string"/>
            <xs:element name="Drzava" type="xs:string"/>
            <xs:element name="PostanskiBroj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTReferenca">
        <xs:sequence>
            <xs:element name="NazivRada" type="xs:string"/>
            <xs:element name="URLRada" type="xs:string"/>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="Autor" type="xs:string"/>
            </xs:sequence>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== ftn-dnb/xws/xws-service/data/example_data/naucni_rad_vise1.xml
<?xml version="1.0" encoding="UTF-8"?>
<NaucniRad xmlns="naucni_rad"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="naucni_rad file:/E:/XML/proj/xws/Schemas/naucni_rad.xsd">
    <NaslovnaStrana>
        <Naslov>Naslov0</Naslov>
        <Autori>
            <Autor>
                <Ime>Ime0</Ime>
                <Prezime>Prezime0</Prezime>
                <EMail>a@a.a</EMail>
                <BrojTelefona>BrojTelefona0</BrojTelefona>
                <ORCID>0000-dddd-dddd-dddd</ORCID>
                <Ustanova>
                    <Naziv>Naziv0</Naziv>
                    <Adresa>
                        <Ulica>Ulica0</Ulica>
                        <Broj>Broj0</Broj>
                        <Grad>Grad0</Grad>
                        <Drzava>Drzava0</Drzava>
                        <PostanskiBroj>PostanskiBroj0</PostanskiBroj>
                    </Adresa>
                </Ustanova>
            </Autor>
            <Autor>
                <Ime>Ime1</Ime>
                <Prezime>Prezime1</Prezime>
                <EMail>a@a.a</EMail>
                <BrojTelefona>BrojTelefona1</BrojTelefona>
                <ORCID>0000-dddd-dddd-dddd</ORCID>
                <Ustanova>
                    <Naziv>Naziv1</Naziv>
                    <Adresa>
                        <Ulica>Ulica1</Ulica>
                        <Broj>Broj1</Broj>
                        <Grad>Grad1</Grad>
                        <Drzava>Drzava1</Drzava>
                        <PostanskiBroj>PostanskiBroj1</PostanskiBroj>
                    </Adresa>
                </Ustanova>
            </Autor>
        </Autori>
    </NaslovnaStrana>
    <Abstrakt>Abstrakt0</Abstrakt>
    <KljucneReci>
        <KljucnaRec>KljucnaRec0</KljucnaRec>
        <KljucnaRec>KljucnaRec1</KljucnaRec>
        <KljucnaRec>KljucnaRec2</KljucnaRec>
        <KljucnaRec>KljucnaRec3</KljucnaRec>
    </KljucneReci>
    <Poglavlja>
        <Poglavlje>
            <Naslov>Naslov1</Naslov>
            <Pasus>
                <Slika>
                    <Sadrzaj>ZGVmYXVsdA==</Sadrzaj>
                    <Naziv>Naziv2</Naziv>
                    <IdReference>IdReference0</IdReference>
                </Slika>
                <Tabela>
                    <Red>
                        <Celija>Celija0</Celija>
                        <Celija>Celija1</Celija>
                    </Red>
                    <Red>
                        <Celija>Celija2</Celija>
                        <Celija>Celija3</Celija>
                    </Red>
                </Tabela>
                <Lista>
                    <Stavka>Stavka0</Stavka>
                </Lista>
                <Tekst>
                    <Sadrzaj>Sadrzaj0</Sadrzaj>
                    <IdReference>IdReference1</IdReference>
                </Tekst>
                <Slika>
                    <Sadrzaj>ZGVmYXVsdA==</Sadrzaj>
                    <Naziv>Naziv3</Naziv>
                    <IdReference>IdReference2</IdReference>
                </Slika>
                <Tabela>
                    <Red>
                        <Celija>Celija4</Celija>
                        <Celija>Celija5</Celija>
                    </Red>
                    <Red>
                        <Celija>Celija6</Celija>
                        <Celija>Celija7</Celija>
                    </Red>
                </Tabela>
                <Lista>
                    <Stavka>Stavka1</Stavka>
                </Lista>
                <Tekst>
                    <Sadrzaj>Sadrzaj1</Sadrzaj>
                    <IdReference>IdReference3</IdReference>
                </Tekst>
            </Pasus>
            <Pasus>
                <Slika>
                    <Sadrzaj>ZGVmYXVsdA==</Sadrzaj>
                    <Naziv>Naziv4</Naziv>
                    <IdReference>IdReference4</IdReference>
                </Slika>
                <Tabela>
                    <Red>
                        <Celija>Celija8</Celija>
                        <Celija>Celija9</Celija>
                    </Red>
                    <Red>
                        <Celija>Celija10</Celija>
                        <Celija>Celija11</Celija>
                    </Red>
                </Tabela>
                <Lista>
                    <Stavka>Stavka2</Stavka>
                </Lista>
                <Tekst>
                    <Sadrzaj>Sadrzaj2</Sadrzaj>
                    <IdReference>IdReference5</IdReference>
                </Tekst>
                <Slika>
                    <Sadrzaj>ZGVmYXVsdA==</Sadrzaj>
                    <Naziv>Naziv5</Naziv>
                    <IdReference>IdReference6</IdReference>
                </Slika>
                <Tabela>
                    <Red>
                        <Celija>Celija12</Celija>
                        <Celija>Celija13</Celija>
                    </Red>
                    <Red>
                        <Celija>Celija14</Celija>
                        <Celija>Celija15</Celija>
                    </Red>
                </Tabela>
                <Lista>
                    <Stavka>Stavka3</Stavka>
                </Lista>
                <Tekst>
                    <Sadrzaj>Sadrzaj3</Sadrzaj>
                    <IdReference>IdReference7</IdReference>
                </Tekst>
            </Pasus>
        </Poglavlje>
    </Poglavlja>
    <Reference>
        <Referenca>
            <NazivRada>NazivRada0</NazivRada>
            <URLRada>URLRada0</URLRada>
            <Autor>Autor0</Autor>
            <Autor>Autor1</Autor>
        </Referenca>
    </Reference>
</NaucniRad>
