=== ftn-dnb/xws/xws-service/data/schemas/poslovni_proces.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/xws/tim5" xmlns="http://www.ftn.uns.ac.rs/xws/tim5">
    <xs:element name="PoslovniProces">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NaucniRadId" type="xs:string"/>
                <xs:element name="PropratnoPismoId" type="xs:string"/>
                <xs:element name="Faza" type="EnumFaza"/>
                <xs:element name="StatusRada" type="EnumStatusRada"/>
                <xs:element name="Recenzenti">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Recenzent" type="CTRecenzent"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="EnumFaza">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ZaReviziju"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumStatusRada">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Obrisan"/>
            <xs:enumeration value="Prihvacen"/>
            <xs:enumeration value="Odbijen"/>
            <xs:enumeration value="UProcesu"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumStatusRecenziranja">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Prihvacen"/>
            <xs:enumeration value="Odbijen"/>
            <xs:enumeration value="Cekanje"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="CTRecenzent">
        <xs:sequence>
            <xs:element name="RecenzentID" type="xs:string"/>
            <xs:element name="Status" type="EnumStatusRecenziranja"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ftn-dnb/xws/xws-service/data/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PoslovniProces xmlns="http://www.ftn.uns.ac.rs/xws/tim5"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/xws/tim5 file:/E:/dev/xws-project/xws-service/data/schemas/poslovni_proces.xsd">
    <NaucniRadId>NaucniRadId0</NaucniRadId>
    <PropratnoPismoId>PropratnoPismoId0</PropratnoPismoId>
    <Faza>ZaReviziju</Faza>
    <StatusRada>Obrisan</StatusRada>
    <Recenzenti>
        <RecenzentID>RecenzentID0</RecenzentID>
        <RecenzentID>RecenzentID1</RecenzentID>
    </Recenzenti>
</PoslovniProces>
