=== ftn-dnb/xws/Schemas/propratno_pismo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="propratno_pismo" xmlns:pp="propratno_pismo">

    <xs:element name="PropratnoPismo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Posaljilac" type="pp:CTAutor"/>
                <xs:element name="Primalac" type="pp:CTAutor"/>
                <xs:element name="Datum" type="xs:date"/>
                <xs:element name="SadrzajPisma" type="xs:string"/>
                <xs:element name="Potpis" type="xs:base64Binary"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="CTAutor">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Ime" type="xs:string"/>
            <xs:element maxOccurs="unbounded" name="Prezime" type="xs:string"/>
            <xs:element name="EMail">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".+@.+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="BrojTelefona" type="xs:string"/>
            <xs:element name="ORCID" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{4}-d{4}-d{4}-d{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Ustanova" type="pp:CTNaucnaUstanova"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTNaucnaUstanova">
        <xs:sequence>
            <xs:element name="Naziv" nillable="false" type="xs:string"/>
            <xs:element name="Adresa" type="pp:CTAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CTAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:string"/>
            <xs:element name="Grad" type="xs:string"/>
            <xs:element name="Drzava" type="xs:string"/>
            <xs:element name="PostanskiBroj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ftn-dnb/xws/Schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PropratnoPismo xmlns="propratno_pismo"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="propratno_pismo file:/E:/XML/proj/xws/Schemas/propratno_pismo.xsd">
    <Posaljilac>
        <Ime>Ime0</Ime>
        <Prezime>Prezime0</Prezime>
        <EMail>a@a.a</EMail>
        <BrojTelefona>BrojTelefona0</BrojTelefona>
        <ORCID>0000-dddd-dddd-dddd</ORCID>
        <Ustanova>
            <Naziv>Naziv0</Naziv>
            <Adresa>
                <Ulica>Ulica0</Ulica>
                <Broj>Broj0</Broj>
                <Grad>Grad0</Grad>
                <Drzava>Drzava0</Drzava>
                <PostanskiBroj>PostanskiBroj0</PostanskiBroj>
            </Adresa>
        </Ustanova>
    </Posaljilac>
    <Primalac>
        <Ime>Ime1</Ime>
        <Prezime>Prezime1</Prezime>
        <EMail>a@a.a</EMail>
        <BrojTelefona>BrojTelefona1</BrojTelefona>
        <ORCID>0000-dddd-dddd-dddd</ORCID>
        <Ustanova>
            <Naziv>Naziv1</Naziv>
            <Adresa>
                <Ulica>Ulica1</Ulica>
                <Broj>Broj1</Broj>
                <Grad>Grad1</Grad>
                <Drzava>Drzava1</Drzava>
                <PostanskiBroj>PostanskiBroj1</PostanskiBroj>
            </Adresa>
        </Ustanova>
    </Primalac>
    <Datum>2006-05-04</Datum>
    <SadrzajPisma>SadrzajPisma0</SadrzajPisma>
    <Potpis>ZGVmYXVsdA==</Potpis>
</PropratnoPismo>
